apiVersion: apps/v1
kind: Deployment
metadata:
  name: doodles-webserver
  namespace: doodles-azure-ns
  labels:
    app: doodles-webservice
    tier: frontend-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doodles-webservice
      tier: frontend-webserver
  template:
    metadata:
      labels:
        app: doodles-webservice
        tier: frontend-webserver
    spec:
      containers:
      - name: webserver
        image:  daniellandau1998/node-webserver:k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        - containerPort: 80
        resources:
          limits: { memory: "256Mi", cpu: "100m" }
        volumeMounts:
        - { mountPath: "/var/project/src/public/assets/doodles", name: image-data }
        envFrom:
          - secretRef: { name: ssl.cert.data }  # SSL certificates
          - secretRef: { name: jwt.rsa.data }   # JWT keys for signing
          - secretRef: { name: jwt.enc.conf }   # JWT keys and configuration for encryption
          - configMapRef: { name: node.webserver.config }
        env:
          - name: SQL_PASSWORD # Password to access sql database
            valueFrom: { secretKeyRef: { key: MYSQL_PASSWORD, name: sql.pass.data  }}
      volumes:
      - name: image-data
        persistentVolumeClaim:
          claimName: image-data-azure-file-claim

---

apiVersion: v1
kind: Service
metadata:
  name: doodles-webserver-svc
  namespace: doodles-azure-ns
  labels:
    app: doodles-webservice
    tier: frontend-webserver
spec:
  selector:
    app: doodles-webservice
    tier: frontend-webserver
  type: LoadBalancer
  ports:
  - { name: https, port: 443, targetPort: 443 }
  - { name: http, port: 80, targetPort: 80 }
