
version: '3.1'

services:
    webserver_bsync:
        depends_on:
            - backend
        image: test:v3
        container_name: developer_server_with_autorefresh
        restart: always
        volumes:
            - "./nodesrc:/var/project/src"
        ports:
            - "3000:3000"
    webserver_dev:
        image: node-webserver:dev
        container_name: backend_webserver_dev
        restart: always
        command: 
            - node
            - webserver.js
        volumes:
            - "./nodesrc:/var/project/src"
        ports:
            - "4000:3000"
volumes:
    src_data: