
version: '3.1'

services:
    backend:
        image: node-webserver:bakcend-dev
        container_name: dev_backend_webserver
        restart: always
        command: 
            - node
            - webserver-dev1.js
        volumes:
            - "./nodesrc:/var/project/src"
        ports:
            - "4000:3000"
volumes:
    src_data: