
version: '3.1'

services:
    backend:
        image: node-webserver:backend-dev
        container_name: dev_backend_webserver
        restart: always
        stdin_open: true
        tty: true
        volumes:
            - "./nodesrc:/var/project/src"
        ports:
            - "4000:3000"
volumes:
    src_data: