apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: daniellandau1998/node-webserver:dev2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: SQL_ENABLE
            value: "false"

---

apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    app: webserver
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30123

#doesn't work on docker for desktop, use port-forward for testing
#kubectl port-forward svc/webserver 6000:3000