apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data
  labels:
    app: doodles-webservice
    tier: backend-database
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteMany
  hostPath:
    path: /var/mysql

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-data-claim
  namespace: doodles-ns
spec:
  storageClassName: ""
  selector:
    matchLabels:
      app: doodles-webservice
      tier: backend-database
  accessModes: 
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi