kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-data-azure-file-claim
  namespace: doodles-azure-ns
spec:
  storageClassName: "default"
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi