apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-azure-file
  labels:
    app: doodles-webservice
    tier: backend-database
    typ: azure
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteMany
  hostPath:
    path: /var/mysql
  #azureDisk:
  #  kind: Managed
  #  diskName: db-data-disk
  #  diskURI: 
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-data-azure-file-claim
  namespace: doodles-azure-ns
spec:
  storageClassName: ""
  selector:
    matchLabels:
      app: doodles-webservice
      tier: backend-database
      typ: azure
  accessModes: 
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi