apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-data-azure-file
  labels:
    app: doodles-webservice
    tier: frontend-webserver
    typ: azure
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteMany
  azureFile:
    secretName: azure.storage.data
    secretNamespace: doodles-azure-ns
    shareName: image-data-fileshare

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: image-data-azure-file-claim
  namespace: doodles-azure-ns
spec:
  storageClassName: ""
  selector:
    matchLabels:
      app: doodles-webservice
      tier: frontend-webserver
      typ: azure
  accessModes: 
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi