apiVersion: v1
kind: ConfigMap
metadata:
  name: node.webserver.config
  namespace: doodles-ns
data:

  # Port on which webserver listen. No value defaults to 80 or 443
  # PORT: 

  # dns and port of the Database
  SQL_HOST: doodles-database-svc.doodles-ns.svc.cluster.local
  SQL_PORT: '3306'

  SQL_DATABASE: node_wp
  SQL_TABLE_NAME: doodle

  # user / pw to access database
  SQL_USER: node-webserver

  # Enables https
  HTTPS_ENABLE: 'true'

  # Enables encryption of the JWT-tokens
  JWT_ENCRYPTION_ENABLE: 'true'
